common: &common
  adapter: mysql2
  username: root
  password: 
  host: localhost
  pool: 5
  timeout: 5000
  
development:
  <<: *common
  database: correlate_development
  
test: &test
  <<: *common
  database: correlate_test


production:
  <<: *common
  database: correlate

cucumber:
  <<: *test
